# Generated by Django 5.1.3 on 2024-12-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0002_alter_blogger_user'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.ManyToManyField(related_name='liked_posts', to='bloggers.blogger'),
        ),
    ]
