# Generated by Django 5.1.3 on 2024-12-16 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('Comment_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('postid', models.IntegerField()),
                ('Comment_text', models.TextField()),
            ],
        ),
    ]
