# Generated by Django 5.1.3 on 2024-12-18 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_date',
            new_name='comment_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_text',
            new_name='comment_text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='postid',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
            preserve_default=False,
        ),
    ]
